import { ImageResponse } from "next/og";

// Branded link-preview card (og:image) shown when the site URL is shared on
// WhatsApp / Telegram / Facebook / X. 1200×630 PNG generated by next/og — no
// binary asset to maintain. Applied site-wide (root segment); the per-page
// og:title / og:description still come from each route's metadata.
export const alt = "رف رف · RafRaf — The digital shelf for every merchant";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

// IBM Plex Sans Arabic (Bold) covers BOTH Arabic and Latin, so the whole card can
// use it. Satori needs an embedded font for Arabic glyphs; we fetch it at render
// time (the image is then cached). If the fetch fails we degrade to the Latin
// wordmark only — never a broken/tofu render. The timeout keeps the build from
// stalling if the CDN is slow/unreachable.
const FONT_URL =
  "https://cdn.jsdelivr.net/npm/@expo-google-fonts/ibm-plex-sans-arabic@latest/IBMPlexSansArabic_700Bold.ttf";

export default async function OpengraphImage() {
  let font: ArrayBuffer | undefined;
  try {
    const res = await fetch(FONT_URL, { signal: AbortSignal.timeout(4000) });
    if (res.ok) font = await res.arrayBuffer();
  } catch {
    /* degrade to the Latin wordmark only */
  }

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: "96px",
          background:
            "linear-gradient(135deg, #0b1326 0%, #0f1b34 55%, #10231f 100%)",
          color: "#dae2fd",
          fontFamily: font ? "Plex" : undefined,
        }}
      >
        {/* kicker: shelf glyph + category */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "22px",
            marginBottom: "36px",
          }}
        >
          <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
            <div
              style={{
                display: "flex",
                width: "70px",
                height: "12px",
                borderRadius: "5px",
                background: "#4edea3",
              }}
            />
            <div
              style={{
                display: "flex",
                width: "70px",
                height: "12px",
                borderRadius: "5px",
                background: "rgba(78,222,163,0.6)",
              }}
            />
            <div
              style={{
                display: "flex",
                width: "70px",
                height: "12px",
                borderRadius: "5px",
                background: "rgba(78,222,163,0.3)",
              }}
            />
          </div>
          <div
            style={{
              display: "flex",
              fontSize: "28px",
              fontWeight: 600,
              letterSpacing: "3px",
              color: "#8fe3bb",
            }}
          >
            POS · INVENTORY · DEBT LEDGER
          </div>
        </div>

        {/* wordmark */}
        <div style={{ display: "flex", alignItems: "baseline", gap: "32px" }}>
          <div
            style={{
              display: "flex",
              fontSize: "150px",
              fontWeight: 800,
              color: "#ffffff",
              lineHeight: 1,
            }}
          >
            RafRaf
          </div>
          {font && (
            <div
              style={{
                display: "flex",
                fontSize: "120px",
                fontWeight: 700,
                color: "#4edea3",
                lineHeight: 1,
              }}
            >
              رف رف
            </div>
          )}
        </div>

        {/* tagline */}
        <div
          style={{
            display: "flex",
            marginTop: "40px",
            fontSize: "44px",
            color: "#bbcabf",
          }}
        >
          The digital shelf for every merchant
        </div>

        <div
          style={{
            display: "flex",
            marginTop: "52px",
            width: "200px",
            height: "14px",
            borderRadius: "7px",
            background: "linear-gradient(90deg, #4edea3, #10b981)",
          }}
        />
      </div>
    ),
    {
      ...size,
      fonts: font
        ? [{ name: "Plex", data: font, weight: 700 as const, style: "normal" as const }]
        : undefined,
    },
  );
}
